POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikphc2thIiwiaWQiOiI2MmM3MmVkZjBlODM4ZTA5NjlkNGFhMGEiLCJpYXQiOjE2NTcyMjc4OTN9.Wh0e8K3Gw2wNtVf5ZlUkPC1Cmp1xw0zV34fL-iaF668

{"author": "Heikki", "title":"Heikin blogi", "url": "www.heiki.se", "likes": 6}